# Generated by Django 4.1.6 on 2023-03-04 06:02

from django.db import migrations, models
import mpesa.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        default=mpesa.models.dict_instance, verbose_name="mpesa results"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MpesaExpress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Amount"
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(max_length=10, verbose_name="MpesaReceiptNumber"),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(verbose_name="TransactionDate"),
                ),
                ("phone", models.PositiveBigIntegerField(verbose_name="PhoneNumber")),
            ],
        ),
    ]
