# Generated by Django 4.1.6 on 2023-03-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mpesa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesaexpress",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="confirmed"),
        ),
        migrations.AddField(
            model_name="mpesaexpress",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
